- name: "k8s ressource: {{ target_namespace }}/configmap/{{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/configmap.yaml') }}"
    apply: yes
  tags:
  - configmap
