- name: "k8s ressource: {{ target_namespace }}/deployment/{{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/deployment.yaml') }}"
    apply: yes
  tags:
  - deployment
