- name: "k8s ressource: {{ target_namespace }}/service/{{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/service.yaml') }}"
    apply: yes
  tags:
  - service