---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace

- name: shiori
  block:
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/statefulset.yml
    tags:
    - statefulset
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  vars:
    app: shiori
    target_namespace: "{{ namespace }}"
    serviceport: 8080
    targetport: 8080
    statefulset_spec: "{{ shiori_statefulset_spec }}"
    volumeclaimtemplates: "{{ shiori_volumeclaimtemplates }}"
    ingress_domain: "{{ shiori_domain }}"
  tags:
  - shiori