---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace
  when: app_liquidsoapstream_enabled or app_mstream_enabled == true

- name: liquidsoap-streamer
  block:
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: liquidsoap-script
      configmap_files: 
        live.liq: "{{ liquidsoap_script }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: nginx-stream
      configmap_files:
        stream.conf: "{{ liquidsoap_nginx_conf }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/deployment.yml
    tags:
    - deployment
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  - include_tasks: ../k8s_common/service.yml
    vars:
      service_name: liquidsoap-srt1
      protocol: UDP
      targetport: 10000
      serviceport: 10000
    when: stream_insecure_enabled == false
    tags:
    - stream-secure
    - service
  - include_tasks: ../k8s_common/service.yml
    vars:
      service_name: liquidsoap-srt2
      protocol: UDP
      targetport: 10001
      serviceport: 10001
    when: stream_insecure_enabled == false
    tags:
    - stream-secure
    - service
  - include_tasks: ../k8s_common/service.yml
    vars:
      service_name: liquidsoap-srt1
      protocol: UDP
      targetport: 10000
      serviceport: 10000
      nodeport: 31000
    when: stream_insecure_enabled == true
    tags:
    - stream-insecure
    - service
  - include_tasks: ../k8s_common/service.yml
    vars:
      service_name: liquidsoap-srt2
      protocol: UDP
      targetport: 10001
      serviceport: 10001
      nodeport: 31001
    when: stream_insecure_enabled == true
    tags:
    - stream-insecure
    - service
  vars:
    app: liquidsoap-streamer
    target_namespace: "{{ namespace }}"
    serviceport: 80
    targetport: 80
    deployment_spec: "{{ streamer_deployment_spec }}"
    ingress_domain: "{{ streamer_domain }}"
    ingress_annotations:
      nginx.ingress.kubernetes.io/enable-global-auth: "false"
  tags:
  - liquidsoap-streamer
  when: app_liquidsoapstream_enabled == true

- name: mstream
  block:
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/pv.yml
    tags:
    - service
  - include_tasks: ../k8s_common/statefulset.yml
    tags:
    - statefulset
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  vars:
    app: mstream
    target_namespace: "{{ namespace }}"
    serviceport: 3000
    targetport: 3000
    statefulset_spec: "{{ mstream_statefulset_spec }}"
    ingress_domain: "{{ mstream_domain }}"
    pv_name: "music"
    pv_storage: "{{ mstream_storage_music }}"
    pv_path: /music
    volumeclaimtemplates: "{{ mstream_volumeclaimtemplates }}"
  tags:
  - mstream
  when: app_mstream_enabled == true