---
namespace: "portal"

portal_domain: "portal.{{ main_domain }}"
letsencrypt_env: "staging"

portal_image: privyplace/privyplaceportal:latest

portal_deployment_spec: |
  containers:
  - name: liquidsoap
    image: {{ portal_image }}
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: nginx-portal
      mountPath: /etc/nginx/conf.d
    - name: config-portal
      mountPath: /etc/portal
  volumes:
  - name: nginx-portal
    configMap:
      name: nginx-portal
  - name: config-portal
    configMap:
      name: config-portal