---
namespace: "db"

postgres_image: postgres:12
postgres_password: None
postgres_pvc_storage: 500M

deployment_spec: |
  containers:
  - name: postgres
    image: "{{ postgres_image }}"
    imagePullPolicy: Always
    env:
    - name: POSTGRES_PASSWORD
      value: "{{ postgres_password }}"
    - name: PGDATA
      value: "/data"
    ports:
    - containerPort: 5432
      protocol: TCP
    volumeMounts:
    - name: postgres-data
      mountPath: /data
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
