---
namespace: "db"

postgres_image: postgres:12
nginx_image: privyplace/nginx:latest
adminer_image: privyplace/adminer:latest

adminer_domain: "adminer.{{ main_domain }}"

postgres_password: None

postgres_volumeclaimtemplates:
  postgres:
    storage: "500M"

postgres_statefulset_spec: |
  containers:
  - name: postgres
    image: "{{ postgres_image }}"
    imagePullPolicy: Always
    env:
    - name: POSTGRES_PASSWORD
      value: "{{ postgres_password }}"
    - name: PGDATA
      value: "/data"
    livenessProbe:
      tcpSocket:
        port: 5432
    readinessProbe:
      tcpSocket:
        port: 5432
    ports:
    - containerPort: 5432
      protocol: TCP
    volumeMounts:
    - name: postgres
      mountPath: /data

adminer_deployment_spec: |
  containers:
  - name: php
    image: {{ adminer_image }}
    imagePullPolicy: Always
    livenessProbe:
      tcpSocket:
        port: 9000
    readinessProbe:
      tcpSocket:
        port: 9000
    ports:
    - containerPort: 9000
      protocol: TCP
  - name: nginx
    image: {{ nginx_image }}
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: nginx-adminer
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-adminer
    configMap:
      name: nginx-adminer