---
namespace: "db"

postgres_image: postgres:12
postgres_password: None
postgres_statefulset_storage: 500M

postgres_statefulset_spec: |
  containers:
  - name: postgres
    image: "{{ postgres_image }}"
    imagePullPolicy: Always
    env:
    - name: POSTGRES_PASSWORD
      value: "{{ postgres_password }}"
    - name: PGDATA
      value: "/data"
    ports:
    - containerPort: 5432
      protocol: TCP
    volumeMounts:
    - name: postgres
      mountPath: /data
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
