---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ app }}
  namespace: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - {{ ingress_domain }}
    secretName: {{ ingress_domain | replace(".", "-") }}-tls
  rules:
  - host: {{ ingress_domain }}
    http:
      paths:
      - backend:
          serviceName: {{ app }}
          servicePort: {{ serviceport }}

