---
# Ingress
- name: ingress mandatory
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress-mandatory.yaml') }}"

- name: ingress service
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress-service.yaml') }}"

# Cert Manager
# https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager-no-webhook.yaml
- name: certmanager
  k8s:
    state: present
    definition: "{{ lookup('template', 'cert-manager.yaml') }}"

- name: letsencrypt issuer
  k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-issuer.yaml') }}"

