---
# Ingress
- name: ingress mandatory
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress-mandatory.yaml') }}"
    apply: yes

- name: ingress service
  k8s:
    state: present
    definition: "{{ lookup('template', 'ingress-service.yaml') }}"
    apply: yes

- include_tasks: ../k8s_common/configmap.yml
  vars:
    target_namespace: ingress-nginx
    configmap_name: "nginx-configuration"
    app: ingress-nginx
    configmap_values:
      global-auth-url: "https://{{ auth_domain }}/auth-0"
      global-auth-signin: "https://{{ auth_domain }}"
      global-auth-response-headers: "{{ auth_headers }}"
  tags:
  - configmap

# Cert Manager
# https://github.com/jetstack/cert-manager/releases/download/v0.12.0/cert-manager-no-webhook.yaml
- name: certmanager
  k8s:
    state: present
    definition: "{{ lookup('template', 'cert-manager.yaml') }}"
    apply: yes

- name: letsencrypt staging issuer
  k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-issuer.yaml') }}"
    apply: yes
  vars:
    letsencrypt_env: "staging"
    letsencrypt_server_url: "{{ letsencrypt_server_url_staging }}"

- name: letsencrypt prod issuer
  k8s:
    state: present
    definition: "{{ lookup('template', 'letsencrypt-issuer.yaml') }}"
    apply: yes
  vars:
    letsencrypt_env: "prod"
    letsencrypt_server_url: "{{ letsencrypt_server_url_prod }}"
