---

- name: "k8s ensure kube-prometheus setup ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  with_fileglob: '00-kube-prometheus/*'

- name: "k8s ensure kube-prometheus workload ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  with_fileglob: '01-kube-prometheus/*'

- name: "k8s ensure {{ namespace }}/ingress/{{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/ingress.yaml') }}"
  vars:
    ingress_namespace: "{{ namespace }}"
    ingress_domain: "{{ grafana_domain }}"
    serviceport: 3000
    app: grafana

- name: "k8s ensure {{ namespace }}ingress {{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/ingress.yaml') }}"
  vars:
    ingress_namespace: "{{ namespace }}"
    ingress_domain: "{{ prometheus_domain }}"
    serviceport: 9090
    app: prometheus-k3s