---

- name: "k8s ensure kube-prometheus setup ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', '00-kube-prometheus/*', wantlist=True) | sort }}"

- name: "k8s ensure kube-prometheus workload ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', '01-kube-prometheus/*', wantlist=True) | sort }}"

- name: "k8s ensure {{ namespace }}/ingress/{{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/ingress.yaml') }}"
  vars:
    target_namespace: "{{ namespace }}"
    ingress_domain: "{{ grafana_domain }}"
    serviceport: 3000
    app: grafana
  tags:
  - ingress

- name: "k8s ensure {{ namespace }}ingress {{ app }}"
  k8s:
    state: present
    definition: "{{ lookup('template', '../k8s_templates/ingress.yaml') }}"
  vars:
    target_namespace: "{{ namespace }}"
    ingress_domain: "{{ prometheus_domain }}"
    serviceport: 9090
    app: prometheus-k3s
  tags:
  - ingress