---

- name: "k8s ensure kube-prometheus setup ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', '00-kube-prometheus/*', wantlist=True) | sort }}"
  tags:
  - setup-monitoring

- name: "k8s ensure kube-prometheus workload ressources"
  k8s:
    state: present
    definition: "{{ lookup('file', item) }}"
  loop: "{{ lookup('fileglob', '01-kube-prometheus/*', wantlist=True) | sort }}"
  tags:
  - setup-monitoring

- include_tasks: ../k8s_common/ingress.yml
  vars:
    target_namespace: "{{ namespace }}"
    ingress_domain: "{{ grafana_domain }}"
    serviceport: 3000
    app: grafana
  tags:
  - ingress

- include_tasks: ../k8s_common/ingress.yml
  vars:
    target_namespace: "{{ namespace }}"
    ingress_domain: "{{ prometheus_domain }}"
    serviceport: 9090
    app: prometheus-k3s
  tags:
  - ingress
