---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace

- name: portal
  block:
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: nginx-portal
      configmap_files:
        portal.conf: "{{ lookup('template', 'nginx-portal.conf', split_lines=False) }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: config-portal
      configmap_files:
        config.yml: "{{ lookup('template', 'config.yml', split_lines=False) }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/deployment.yml
    tags:
    - deployment
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  vars:
    app: portal
    target_namespace: "{{ namespace }}"
    serviceport: 8080
    targetport: 8080
    deployment_spec: "{{ portal_deployment_spec }}"
    ingress_domain: "{{ portal_domain }}"
  tags:
  - portal