---
namespace: "infra"

sshd_image: privyplace/sshd:latest
sshd_nodeport: 30000
authorized_keys: ""

sshd_deployment_spec: |
  containers:
  - name: sshd
    image: {{ sshd_image }}
    imagePullPolicy: Always
    livenessProbe:
      tcpSocket:
        port: 22
    readinessProbe:
      tcpSocket:
        port: 22
    ports:
    - containerPort: 22
      protocol: TCP
    volumeMounts:
    - name: sshd-authorized-keys
      mountPath: /root/.ssh/authorized_keys
      subPath: authorized_keys
  volumes:
  - name: sshd-authorized-keys
    configMap:
      name: sshd-authorized-keys

organizr_image: privyplace/organizr:latest
organizr_domain: "{{ main_domain }}"
nginx_image: privyplace/nginx:latest
organizr_statefulset_storage: 100M

organizr_statefulset_spec: |
  containers:
  - name: php
    image: {{ organizr_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 9000
      protocol: TCP
    livenessProbe:
      tcpSocket:
        port: 9000
    readinessProbe:
      tcpSocket:
        port: 9000
    volumeMounts:
    - name: www
      mountPath: /www
    - name: organizr
      mountPath: /data
    lifecycle:
      preStop:
        exec:
          command: ["/prestop.sh"]
  - name: nginx
    image: {{ nginx_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    volumeMounts:
    - name: www
      mountPath: /www
    - name: nginx-organizr
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: www
    emptyDir: {}
  - name: nginx-organizr
    configMap:
      name: nginx-organizr
