---
namespace: "infra"

auth_domain: "auth.{{ main_domain }}"
portal_domain: "{{ main_domain }}"
organizr_domain: "{{ auth_domain }}"


sshd_image: privyplace/sshd:latest
nginx_image: privyplace/nginx:latest
organizr_image: privyplace/organizr:latest
portal_image: privyplace/privyplaceportal:latest

sshd_nodeport: 30000
sshd_authorized_keys: ""

organizr_statefulset_storage: 100M

sshd_deployment_spec: |
  containers:
  - name: sshd
    image: {{ sshd_image }}
    imagePullPolicy: Always
    livenessProbe:
      tcpSocket:
        port: 22
    readinessProbe:
      tcpSocket:
        port: 22
    ports:
    - containerPort: 22
      protocol: TCP
    volumeMounts:
    - name: sshd-authorized-keys
      mountPath: /root/.ssh/authorized_keys
      subPath: authorized_keys
  volumes:
  - name: sshd-authorized-keys
    configMap:
      name: sshd-authorized-keys

organizr_statefulset_spec: |
  containers:
  - name: php
    image: {{ organizr_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 9000
      protocol: TCP
    livenessProbe:
      tcpSocket:
        port: 9000
    readinessProbe:
      tcpSocket:
        port: 9000
    volumeMounts:
    - name: www
      mountPath: /www
    - name: organizr
      mountPath: /data
    lifecycle:
      preStop:
        exec:
          command: ["/prestop.sh"]
  - name: nginx
    image: {{ nginx_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    volumeMounts:
    - name: www
      mountPath: /www
    - name: nginx-organizr
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: www
    emptyDir: {}
  - name: nginx-organizr
    configMap:
      name: nginx-organizr

portal_deployment_spec: |
  containers:
  - name: liquidsoap
    image: {{ portal_image }}
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: nginx-portal
      mountPath: /etc/nginx/conf.d
    - name: config-portal
      mountPath: /etc/portal
  volumes:
  - name: nginx-portal
    configMap:
      name: nginx-portal
  - name: config-portal
    configMap:
      name: config-portal