---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace

- name: Postgresql
  block:
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/statefulset.yml
    tags:
    - statefulset
  vars:
    app: "postgres"
    target_namespace: "{{ namespace }}"
    serviceport: 5432
    targetport: 5432
    statefulset_spec: "{{ postgres_statefulset_spec }}"
    statefulset_storage: "{{ postgres_statefulset_storage }}"
