---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace

- name: Postgresql
  block:
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/pvc.yml
    tags:
    - pvc
  - include_tasks: ../k8s_common/deployment.yml
    tags:
    - deployment
  vars:
    app: "postgres"
    target_namespace: "{{ namespace }}"
    pvc_storage: "{{ postgres_pvc_storage }}"
    serviceport: 5432
    targetport: 5432
