---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ configmap_name | default(app)}}
  namespace: {{ target_namespace }}
data:
  {{ configmap_filename }}: |
    {{ configmap_content | indent(width=4) }}
