---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ deployment_name | default(app)}}
  namespace: {{ target_namespace }}
  labels:
    app: {{ deployment_name | default(app)}}
spec:
{% if deployment_replicas is defined %}
  replicas: {{ deployment_replicas }}
{% endif %}
  selector:
    matchLabels:
      app: {{ deployment_name | default(app)}}
  template:
    metadata:
      labels:
        app: {{ deployment_name | default(app)}}
    spec:
      {{ deployment_spec | indent(width=6) }}