---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ deployment_name }}
  namespace: {{ deployment_namespace }}
  labels:
    app: {{ deployment_name }}
spec:
  replicas: {{ deployment_replicas }}
  selector:
    matchLabels:
      app: {{ deployment_name }}
  template:
    metadata:
      labels:
        app: {{ deployment_name }}
    spec:
      {{ deployment_spec | indent(width=6) }}