---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ ingress_name | default(app)}}
  namespace: {{ target_namespace }}
  labels:
    app: {{ ingress_partof | default(app)}}
    app.kubernetes.io/name: "{{ ingress_name | default(app)}}"
    app.kubernetes.io/part-of: "{{ ingress_partof | default(app)}}"
    app.kubernetes.io/managed-by: privyplace
{% if ingress_labels is defined %}{% for key, value in ingress_labels.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}{% endif %}
{% if labels is defined %}{% for key, value in labels.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}{% endif %}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-{{ letsencrypt_env }}
{% if ingress_annotations is defined %}{% for key, value in ingress_annotations.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}{% endif %}
spec:
  tls:
  - hosts:
    - {{ ingress_domain }}
    secretName: {{ ingress_domain | replace(".", "-") }}-tls
  rules:
  - host: {{ ingress_domain }}
    http:
      paths:
      - path: {{ ingress_path | default('/')}}
        backend:
          serviceName: {{ service_name | default(app)}}
          servicePort: {{ serviceport }}

