---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ ingress_name | default(app)}}
  namespace: {{ target_namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-{{ letsencrypt_env }}
{% if ingress_annotations is defined %}{% for key, value in ingress_annotations.items() %}
    {{ key }}: {{ value }}
{% endfor %}{% endif %}
spec:
  tls:
  - hosts:
    - {{ ingress_domain }}
    secretName: {{ ingress_domain | replace(".", "-") }}-tls
  rules:
  - host: {{ ingress_domain }}
    http:
      paths:
      - backend:
          serviceName: {{ service_name | default(app)}}
          servicePort: {{ serviceport }}

