apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ pv_name | default(app ~ '-pv')}}
  namespace: {{ target_namespace }}
  labels:
    app: {{ pv_partof | default(app)}}
    app.kubernetes.io/name: "{{ pv_name | default(app ~ '-pv')}}"
    app.kubernetes.io/part-of: "{{ pv_partof | default(app)}}"
    app.kubernetes.io/managed-by: privyplace
{% if pv_labels is defined %}{% for key, value in pv_labels.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}{% endif %}
{% if labels is defined %}{% for key, value in labels.items() %}
    {{ key }}: "{{ value }}"
{% endfor %}{% endif %}
spec:
  storageClassName: {{ pv_storageclass_name | default('host-path') }}
  capacity:
    storage: {{ pv_storage }}
  accessModes:
    - {{ pv_accessmode | default('ReadWriteOnce') }}
  hostPath:
    path: "{{ pv_path }}"