apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ pvc_name | default(app ~ '-pvc')}}
  namespace: {{ target_namespace }}
spec:
  accessModes:
    - {{ pvc_accessmode | default('ReadWriteOnce')}}
  storageClassName: local-path
  resources:
    requests:
      storage: {{ pvc_storage }}