---
apiVersion: v1
kind: Service
metadata:
  name: {{ service_name | default(app)}}
  namespace: {{ target_namespace }}
spec:
  ports:
  - port: {{ serviceport }}
    targetPort: {{ targetport }}
    protocol: {{ protocol | default('TCP')}}
{% if nodeport is defined %}
    nodePort: {{ nodeport }}
{% endif %}
  selector:
    app: {{ deployment_name | default(app)}}
  type: {% if nodeport is defined  %}NodePort{% else %}ClusterIP{% endif %}