---
- include_tasks: ../k8s_common/namespace.yml
  vars:
    target_namespace: "{{ namespace }}"
  tags:
  - namespace

- name: ansible-executor
  block:
  - include_tasks: ../k8s_common/configmap.yml
    tags:
    - configmap
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/deployment.yml
    tags:
    - deployment
  - name: Wait for port {{ sshd_nodeport }} to become open on the host
    wait_for:
      port: "{{ sshd_nodeport }}"
      timeout: 60
  vars:
    app: ansible-executor
    target_namespace: "{{ namespace }}"
    configmap_name: sshd-authorized-keys
    configmap_files:
      authorized_keys: "{{ sshd_authorized_keys }}"
    serviceport: 22
    targetport: 22
    nodeport: "{{ sshd_nodeport }}"
    deployment_spec: "{{ sshd_deployment_spec }}"
  tags:
  - ansible-executor

- name: organizr
  block:
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: "nginx-{{ app }}"
      configmap_files:
        php.conf: "{{ lookup('template', 'nginx-organizr.conf', split_lines=False) }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/statefulset.yml
    tags:
    - statefulset
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  vars:
    app: organizr
    target_namespace: "{{ namespace }}"
    serviceport: 8080
    targetport: 8080
    statefulset_spec: "{{ organizr_statefulset_spec }}"
    statefulset_storage: "{{ organizr_statefulset_storage }}"
    ingress_domain: "{{ organizr_domain }}"
    ingress_annotations:
      nginx.ingress.kubernetes.io/enable-global-auth: "false"
  tags:
  - organizr

- name: portal
  block:
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: nginx-portal
      configmap_files:
        portal.conf: "{{ lookup('template', 'nginx-portal.conf', split_lines=False) }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/configmap.yml
    vars:
      configmap_name: config-portal
      configmap_files:
        config.yml: "{{ lookup('template', 'config-portal.yml', split_lines=False) }}"
    tags:
    - configmap
  - include_tasks: ../k8s_common/service.yml
    tags:
    - service
  - include_tasks: ../k8s_common/deployment.yml
    tags:
    - deployment
  - include_tasks: ../k8s_common/ingress.yml
    tags:
    - ingress
  vars:
    app: portal
    target_namespace: "{{ namespace }}"
    serviceport: 8080
    targetport: 8080
    deployment_spec: "{{ portal_deployment_spec }}"
    ingress_domain: "{{ portal_domain }}"
  tags:
  - portal