---
namespace: "stream"

app_liquidsoapstream_enabled: true
app_mstream_enabled: true

streamer_domain: "stream.{{ main_domain }}"
mstream_domain: "music.{{ main_domain }}"

liquidsoap_image: privyplace/liquidsoap:master-1.5.0-2462
nginx_image: privyplace/nginx:latest
mstream_image: privyplace/mstream:latest

mstream_storage_data: 200M
mstream_storage_music: 10Gi
mstream_volumeclaimtemplates:
  mstream:
    storage: "{{ mstream_storage_data }}"
  music:
    storageclass: host-path
    storage: "{{ mstream_storage_music }}"

liquidsoap_script: "{{ lookup('url', 'https://raw.githubusercontent.com/mbugeia/srt2hls/v0.0.1/radio/live.liq', split_lines=False) }}"
liquidsoap_nginx_conf: "{{ lookup('url', 'https://raw.githubusercontent.com/mbugeia/srt2hls/v0.0.1/nginxhls/stream.conf', split_lines=False) | regex_replace('liquidsoap', 'localhost')}}"

# Setting this to true will make the srt services bind to a Nodeport
# Since SRT connection is not yet secure in Liquidsoap,that could 
# allow anyone to stream content if your firewall rules are not properly 
# set. So only activate this if you know what you are doing.
stream_insecure_enabled: false

streamer_deployment_spec: |
  containers:
  - name: liquidsoap
    image: {{ liquidsoap_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 8500
      protocol: TCP
    - containerPort: 8081
      protocol: TCP
    - containerPort: 9090
      protocol: TCP
    - containerPort: 10000
      protocol: UDP
    - containerPort: 10001
      protocol: UDP
    volumeMounts:
    - name: hls
      mountPath: /hls
    - name: liquidsoap-script
      mountPath: /radio
  - name: nginx
    image: {{ nginx_image }}
    imagePullPolicy: Always
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      httpGet:
        path: /live.m3u8
        port: 80
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: hls
      mountPath: /hls
    - name: nginx-stream
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: hls
    emptyDir: {}
  - name: liquidsoap-script
    configMap:
      name: liquidsoap-script
  - name: nginx-stream
    configMap:
      name: nginx-stream

mstream_statefulset_spec: |
  containers:
  - name: mstream
    image: {{ mstream_image }}
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 3000
    volumeMounts:
    - name: mstream
      mountPath: /data
    - mountPath: /music
      name: music
