---
namespace: "searx"

searx_domain: "search.{{ main_domain }}"
letsencrypt_env: "staging"

searx_image: privyplace/searx:latest

searx_deployment_spec: |
  containers:
  - name: searx
    image: {{ searx_image }}
    imagePullPolicy: Always
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
