---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ letsencrypt_env }}
spec:
  acme:
    server: {{ letsencrypt_server_url }}
    email: {{ letsencrypt_email }}
    privateKeySecretRef:
      name: letsencrypt-{{ letsencrypt_env }}
    solvers:
    - http01:
        ingress:
          class: nginx
